refactor: improve template selection process in pbd.sh script (#3)

diff --git a/pbd_configs/pbd_shell b/pbd_configs/pbd_shell
--- a/pbd_configs/pbd_shell
+++ b/pbd_configs/pbd_shell
@@ -18,6 +18,7 @@ build_container() {
 
 }
 
+
 delete_pbd() {
 
     read -p "Are you sure you want to delete PBD? [y/N] " answer
@@ -29,6 +30,7 @@ delete_pbd() {
         echo "Aborted."
     fi
 }
+
 
 drf_template() {
     read -p "Install Django + DRF [Y/n] " agreesing
@@ -51,7 +53,7 @@ drf_template() {
 }
 
 
-gql_template() (
+gql_template() {
 
     read -p "Install Django + Graphene [Y/n] " agreesing
     if [ "$agreesing" = "n" ] || [ "$agreesing" = "N" ] || [ "$agreesing" = "no" ] || [ "$agreesing" = "No" ] || [ "$agreesing" = "NO" ]; then
@@ -71,4 +73,89 @@ gql_template() (
 
     xdg-open https://github.com/lyaguxafrog/python-backend-devcontainers/blob/release/docs/DJANGO_GRAPHENE.md
 
-)
+}
+
+
+flask_template() {
+    echo "Flask in develop!"
+}
+
+
+handle_arguments() {
+    while getopts ":t:" opt; do
+        case ${opt} in
+            t)
+                template=$OPTARG
+                ;;
+            \?)
+                echo "Invalid option: -$OPTARG" 1>&2
+                exit 1
+                ;;
+            :)
+                echo "Option -$OPTARG requires an argument." 1>&2
+                exit 1
+                ;;
+        esac
+    done
+    shift $((OPTIND -1))
+}
+
+
+choose_template() {
+    if [ -z "$template" ]; then
+        echo "Choose a template:"
+        echo "1. Django + DRF"
+        echo "2. Django + Graphene"
+        echo "3. Flask"
+        read -p "Enter the number of the template: " template_number
+        case $template_number in
+            1)
+                template="drf"
+                ;;
+            2)
+                template="gql"
+                ;;
+            3)
+                template="flask"
+                ;;
+            *)
+                echo "Invalid choice."
+                exit 1
+                ;;
+        esac
+    fi
+}
+
+
+use_template() {
+    case $template in
+        drf)
+            drf_template
+            ;;
+        gql)
+            gql_template
+            ;;
+        flask)
+            flask_template
+            ;;
+        *)
+            echo "Invalid template."
+            exit 1
+            ;;
+    esac
+}
+
+
+case "$1" in
+    new)
+        handle_arguments "$3"
+
+        choose_template
+
+        use_template
+        ;;
+    *)
+        echo "Invalid command. Use 'pbd.sh new' or 'pbd.sh new -t <template>'"
+        exit 1
+        ;;
+esac
